### ISSUE TITLE
Appreciate the ARM cross-compiler toolchain

### ISSUE THREAD

**Issue by istathar** [lantw44/copr-rpm-spec#3]
Just wanted to say thanks for the **arm-linux-gnueabihf-gcc** builds you have in your COPR. First thing I've managed to use that worked to build a static binary to test under _qemu-arm_ and then run on a Raspberry Pi 3 target

(notably the **arm-none-eabi-{gcc,newlib}-cs** in Fedora didn't work, which was a bit surprising. Your architecture choice is probably what I really needed but grinding through the crosstool-NG sequence looked like an appalling grind. So thanks)

Two questions:

1) can we get this into Fedora?

2) do you think I should care that this is `armv7-a` and not a newer core (let alone `aarch64`)? Presumably 32-bit ARMv7-A is _fine_, but hard to know who to ask. As far as I can tell Raspbian is still only building a `armv7l` kernel but presumably that'll change at some point; there are registers sitting there begging to be used it seems.

Cheers,

AfC

**Comment by lantw44** [comment]
> (notably the arm-none-eabi-{gcc,newlib}-cs in Fedora didn't work, which was a bit surprising. Your architecture choice is probably what I really needed but grinding through the crosstool-NG sequence looked like an appalling grind. So thanks)

Yes, I remember that all non-MinGW cross compilers provided by Fedora can only be used to compile kernel, and ths is why I started building RPM packages for my personal use. I used to use crosstool-NG, but I found that maintaining the installation was not easy because of unexpected build failure.

> Two questions:
> can we get this into Fedora?

I don't know. I never try to do it, and I think I will not have time to track upstream security patch and bugfix update if it is required. I take 'the most simple way' to package them. No non-needed RPM macros and subpackages. No security and bugfix patch unless the released version cannot be built without it. 

> do you think I should care that this is armv7-a and not a newer core (let alone aarch64)? Presumably 32-bit ARMv7-A is fine, but hard to know who to ask. As far as I can tell Raspbian is still only building a armv7l kernel but presumably that'll change at some point; there are registers sitting there begging to be used it seems.

Do you mean you need features that cannot be enabled by passing additional options to gcc?

**Comment by istathar** [comment]
> I never try to do it, and I think I will not have time to track upstream security patch and bugfix update if it is required.

Might be worth the exercise, if you've never tried it. You're not on your own; the point of putting something in a distro is that other people can help maintain the package to a high standard.

Thanks again, good luck.

AfC
